name: SimpleTPA
version: 0.0.2
main: xyz.misilelaboratory.simpletpa.SimpleTPA
api-version: 1.19
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.20
  - io.github.monun:kommand-core:2.14.0
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1
